<?php include "header.php" ?>
    <!-- header widhdraw -->
    <header class="header_bankcard position-fixed w-100  bg-white">
        <div class="px-3 py-3 border  shadow ">

            <img class="chevron-left-bank pt-1" src="img/left_back.png" alt="">
            <div class="text-center">
                <strong>AFP</strong>
            </div>
        </div>
    </header>
    <div class="vh_top "></div>
    <main class="main_afp">
        <section style="padding: 20px;">
            <div class="common_html_wrap">
                <p><strong>The TikTok mobile app allows users to create short videos, which often feature music in the
                        background and can be sped up, slowed down, or edited with a filter.&nbsp;They can also add
                        their own sound on top of the background music. To create a music video with the app, users can
                        choose background music from a wide variety of&nbsp;<a
                            href="https://en.wikipedia.org/wiki/Music_genre" title="Music genre">music genres</a>, edit
                        with a filter and record a 15-second video with speed adjustments before uploading it to share
                        with others on TikTok or other social platforms.They can also film short lip-sync videos to
                        popular songs.&nbsp; </strong></p>

                <p><strong>The "For You" page on TikTok is a feed of videos that are recommended to users based on their
                        activity on the app. Content is generated by TikTok's artificial intelligence (AI) depending on
                        the content a user liked, interacted with, or searched. This is in contrast to other social
                        networks' algorithms basing such content off of the user's relationships with other users and
                        what they liked or interacted with.Users can also choose to add to favorites or select "not
                        interested" on videos for their page. TikTok combines the user's enjoyed content to provide
                        videos that they would also enjoy. Users and their content can only be featured on the "for you"
                        page if they are 16 or over as per TikTok policy. Users under 16 will not show up under the "for
                        you" page, the sounds page, or under any hashtags.</strong></p>

                <p><strong>The app's "react" feature allows users to film their reaction to a specific video, over which
                        it is placed in a small window that is movable around the screen.&nbsp;Its "duet" feature allows
                        users to film a video aside another video.&nbsp;The "duet" feature was another trademark of
                        musical.ly. The duet feature is also only able to be used if both parties adjust the privacy
                        settings.</strong></p>

                <p><strong>Videos that users do not want to post yet can be stored in their "drafts." The user is
                        allowed to see their "drafts" and post when they find it fitting.The app allows users to set
                        their accounts as "private." When first downloading the app, the user's account is public by
                        default. The user can change to private in their settings. Private content remains visible to
                        TikTok, but is blocked from TikTok users who the account holder has not authorized to view their
                        content.Users can choose whether any other user, or only their "friends," may interact with them
                        through the app via comments, messages, or "react" or "duet" videos.Users also can set specific
                        videos to either "public," "friends only," or "private" regardless if the account is private or
                        not.</strong></p>

                <p><strong>Users are also allowed to report accounts depending on the account's content, either being
                        spam or inappropriate. In TikTok's support center under "For Parents," they reassure the parents
                        that inappropriate content for their children can be blocked and reported.</strong></p>

                <p><strong>When users follow other users, a "following" page is located on the left of the "for you"
                        page. This is a page only to see the videos from the accounts a user follows. Users can also add
                        videos, hashtags, filters, and sounds to their "saved" section. When creating a video, they can
                        refer to their saved section, or create a video straight from it. This section is visible only
                        to the user on their profile allowing them to refer to any video, hashtag, filter, or sound they
                        have previously saved.</strong></p>

                <p><strong>Users can also send their friends videos,&nbsp;<a href="https://en.wikipedia.org/wiki/Emoji"
                            title="Emoji">emojis</a>, and messages with direct messaging. TikTok has also included a
                        feature to create a video based on the user's comments. Influencers often use the "live"
                        feature. This feature is only available for those who have at least 1,000 followers and are over
                        16 years old. If over 18, the user's followers can send virtual "gifts" that can be later
                        exchanged for money.</strong></p>

                <p><strong>One of the newest features as of 2020 is the "Virtual Items" of "Small Gestures" feature.
                        This is based on China's big practice of social gifting. Since this feature was added, many
                        beauty companies and brands created a TikTok account to participate and advertise this feature.
                        With&nbsp;<a href="https://en.wikipedia.org/wiki/COVID-19_lockdown"
                            title="COVID-19 lockdown">COVID-19 lockdown</a>&nbsp;in the United States, social gifting
                        has grown in popularity. According to a TikTok representative, the campaign was launched as a
                        result of the lockdown, "to build a sense of support and encouragement with the TikTok community
                        during these tough times."</strong></p>

                <p><strong>TikTok announced a "family safety mode" in February 2020 for parents to be able to control
                        their children's digital well-being. There is a screen time management option, restricted mode,
                        and can put a limit on direct messages.</strong></p>

                <p><strong>The app expanded its parental controls feature called "Family Pairing" in September 2020 to
                        provide parents and guardians with educational resources to understand what children on TikTok
                        are exposed to. Content for the feature was created in partnership with online safety
                        nonprofit,&nbsp;<a href="https://en.wikipedia.org/wiki/Internet_Matters"
                            title="Internet Matters">Internet Matters</a>.</strong></p>

                <p><strong>In October 2021, TikTok launched a test feature that allows users to directly tip certain
                        creators. Accounts of users that are of age, have at least 100,000 followers and agree to the
                        terms can activate a "Tip" button on their profile, which allows followers to tip any amount,
                        starting from $1.</strong></p>

                <p><strong>In December 2021, TikTok started beta-testing Live Studio, a streaming software that would
                        let users broadcast applications open on their computers, including games. The software also
                        launched with support for mobile and PC streaming.However, a few days later, users on Twitter
                        discovered that the software allegedly uses code from the open-source&nbsp;<a
                            href="https://en.wikipedia.org/wiki/OBS_Studio" title="OBS Studio">OBS Studio</a>. OBS made
                        a statement saying that, under the&nbsp;<a
                            href="https://en.wikipedia.org/wiki/GNU_General_Public_License"
                            title="GNU General Public License">GNU GPL</a>&nbsp;version 2, TikTok has to make the code
                        of Live Studio publicly available if it wants to use any code from OBS.</strong></p>

                <p><strong>In May 2022, TikTok announced TikTok Pulse, an ad revenue sharing program. It covers the "top
                        4% of all videos on TikTok" and is only available to creators with more than 100,000 followers.
                        If an eligible creator's video reaches the top 4%, they will receive a 50% share of the revenue
                        from ads displayed with the video.</strong></p>

                <p>&nbsp;</p>
            </div>
        </section>
    </main>
    <div class="vh_top mb-5"></div>
