<?php include "header.php" ?>
    <header class="header_deposit_usd position-fixed w-100 bg-white">
        <div class="px-3 py-3 border shadow ">
            <img class="chevron-left " src="img/left_back.png" alt="">
            <div class="text-center">
                <span>Beginner Tutorial</span>
            </div>
        </div>
    </header>
    <div class="vh_top "></div>
    <!-- beginners tutorial -->
    <div class="container-fluid Beginner_guide px-4 pt-5">
        <p>
            <strong>
                Investment on this platform opens a three-level generation model. The third level means that the agent
                can get the commission share of the third level, and the part that exceeds the third level can not get
                the commission share. For example, if you are a member A of this platform, you will have the agency
                right after you perform the task of purchasing. The system will automatically form your member center
                and promote the exclusive QR code. Share your exclusive QR code by yourself. B will register as a member
                by scanning the QR code. After performing the purchasing task, A will get B’s commission 20%.
            </strong>
        </p>
        <p>
            <strong>
                At the same time, the system will automatically form B's member center and exclusive QR code. C
                registered as a member by scanning the QR code, and after performing the purchasing task, B will receive
                20% of C's commission. A gets 10% of C; and so on, if D becomes a member through C, C gets 20%, B gets
                10%, and A gets 5%.
            </strong>
        </p>
        <p>
            <strong>
                Reminder: The commission rewards generated by all agents offline members are issued by this platform,
                and will not affect the commissions of all agents and offline members!
            </strong>
        </p>
    </div>
    <div class="vh_top mb-5"></div>
